/*
 * All rights reserved. (C) Copyright 2009, Trinity College Dublin
 */
/**
 * The classes in this package are sorting the rows of a table
 * based on the order generated by the <em>New Hierarchical Clustering</em> node.
 */
@Nonnull
@CheckReturnValue
package ie.tcd.imm.hits.knime.util.sortby;

import javax.annotation.CheckReturnValue;
import javax.annotation.Nonnull;

